-- AlterTable
ALTER TABLE "User" ADD COLUMN IF NOT EXISTS "address" TEXT;
ALTER TABLE "User" ADD COLUMN IF NOT EXISTS "city" TEXT;
ALTER TABLE "User" ADD COLUMN IF NOT EXISTS "state" TEXT;
ALTER TABLE "User" ADD COLUMN IF NOT EXISTS "country" TEXT;
ALTER TABLE "User" ADD COLUMN IF NOT EXISTS "latitude" DOUBLE PRECISION;
ALTER TABLE "User" ADD COLUMN IF NOT EXISTS "longitude" DOUBLE PRECISION;
ALTER TABLE "User" ADD COLUMN IF NOT EXISTS "phoneNumber" TEXT;

-- AlterTable
ALTER TABLE "Restaurant" ADD COLUMN IF NOT EXISTS "address" TEXT;
ALTER TABLE "Restaurant" ADD COLUMN IF NOT EXISTS "city" TEXT;
ALTER TABLE "Restaurant" ADD COLUMN IF NOT EXISTS "state" TEXT;
ALTER TABLE "Restaurant" ADD COLUMN IF NOT EXISTS "country" TEXT;
ALTER TABLE "Restaurant" ADD COLUMN IF NOT EXISTS "latitude" DOUBLE PRECISION;
ALTER TABLE "Restaurant" ADD COLUMN IF NOT EXISTS "longitude" DOUBLE PRECISION;
ALTER TABLE "Restaurant" ADD COLUMN IF NOT EXISTS "phoneNumber" TEXT;
